### ISSUE TITLE
Numeros en Assembly

### ISSUE THREAD

**Issue by Hernan4444** [IIC2343-2016-2/syllabus#10]
Los números que aparezcan en data o code del assembly estaran codificados en forma decimal o pueden aparecer en hexa o en binario? En el caso de que sea así, cuales serian los formatos para indicar que el numero es hexa o binario?

**Comment by FranLucchini** [comment]
Pueden estar en hexa y binario, el formato está especificado en el enunciado del assembler.

**Comment by Hernan4444** [comment]
Gracias, no me di cuenta de eso :+1:
