### ISSUE TITLE
Sobre el status y el clock

### ISSUE THREAD

**Issue by perojas3** [IIC2343-2016-2/syllabus#12]
Tengo la siguiente duda. Veran hasta ahora en el programa, cada vez que hemos tenido que interactuar con el clock, siempre nos han entregado un archivo que lo usa, sin que nosotros tengamos que manipuarlo (Reg,PC,Ram). Pero ahora el status tambien usa el clock, y no nos han entregado un status predeterminado, desearia saber ¿Como operamos con el status y el clock?

**Comment by FranLucchini** [comment]
Saludos, el componente Status es finalmente un registro. El hint que les puedo dar es revisar el archivo que tienen que es un registro.
