### ISSUE TITLE
Me quedan una duda respecto a la ALU y sus salidas C, Z y N

### ISSUE THREAD

**Issue by perojas3** [IIC2343-2016-2/syllabus#13]
Tengo una duda  que me quedó de la entrega 1 , sobre la salida C, Z y N de la alu.
Entiendo que C es el carrie de la suma, que Z se entrega si los 2 numeros son iguales en la resta. Y que  N es el negativo que queda en la resta.
Pero no estoy seguro de cuando mostrarlos, ¿La ALU solo entra C si se esta sumando, y Z o N si se esta restando, o se entregan siempre sin importar la operacion actual de la ALU?

**Comment by FranLucchini** [comment]
Para esta entrega deben implementar la instrucción CMP (sale en la sección 4 del enunciado del assembler) que para actualizar el registro status ejecutando resta entre ambos operandos. Por eso, C, Z y N se actualizan al restar de la instrucción CMP.

**Comment by perojas3** [comment]
Eso no responde mi pregunta. Solo quiero saber ¿El C aparece solo cuando a la ALU le llega la señal de la suma? Y ¿El Z y el N solo aparecen cuando a la ALU le llega la señal de la resta?

**Comment by FranLucchini** [comment]
No, estan constantemente guardados en el registro estatus y al hacer la instrucción CMP se actualizan sus valores.

**Comment by Hernan4444** [comment]
Solo para confirmar, si uso funciones de salto por condición pero jamás use CMP, entonces los valores de c, z  y n serian los originales es decir 0??

**Comment by FranLucchini** [comment]
Exactamente
