### ISSUE TITLE
Crear archivo .exe

### ISSUE THREAD

**Issue by andersskog** [IIC2343-2016-2/syllabus#15]
Para crear el archivo ejecutable estoy utilizando pyinstaller, que al comprimir los archivos y ejecutar el ejecutable me tira lo siguiente:

<img width="575" alt="screen shot 2016-09-20 at 7 32 50 pm" src="https://cloud.githubusercontent.com/assets/13801374/18691284/d226eefa-7f60-11e6-9b27-248853ccb3c2.png">

He buscado la solución y nada, alguna idea? Existe una mejor forma de crear un ejecutable para código en python.

Gracias!

**Comment by FranLucchini** [comment]
Uno de sus compañeros, @lileiva, me habló de la librería [py2exe](http://www.py2exe.org/)
