### ISSUE TITLE
ADD B, Lit en assembler entrega 2

### ISSUE THREAD

**Issue by selira** [IIC2343-2016-2/syllabus#18]
Estimados, cómo hago la operación ADD B,Lit que sale especificada en el assembler? Porque no se puede hacer en un sólo ciclo del clock, entonces tengo que hacer más de una instrucción cuando sale esa operación? Además que no se pude usar el registro A porque estaría cambiándole el valor.
Saludos

**Comment by FranLucchini** [comment]
Descubrir cómo hacerlo en un ciclo del clock es parte de lo que deben
descubrir en la entrega. Pero lee bien lo que hace esa instrucción,  porque
no hace B + Literal.

**Comment by selira** [comment]
Cierto, no leí la descripción jaja gracias
