### ISSUE TITLE
Problema con el NOP

### ISSUE THREAD

**Issue by perojas3** [IIC2343-2016-2/syllabus#19]
Hoy fui a hablar con el profesor a su oficina y nos surgio la siguiente duda. Es acerca del NOP. No debe cambiar nada, incluyendo el resultado del status. Y alli es donde esta el problema. Lo que se deberia hacer en este instante es cargar 0 en el load del status. Pero el status no tiene load en el esquema que nos entregaron.
¿Como podemos hacer eso?

**Comment by FranLucchini** [comment]
Eso es parte de los problemas que deben enfrentar en la entrega. Pero como hint les puedo decir que pueden usar el componente reg para armar este registro.

**Comment by perojas3** [comment]
¿Pero podemos agregar una coneccion que no este en el esquema?

**Comment by FranLucchini** [comment]
Por supuesto

**Comment by selira** [comment]
No se pueden ingorar simplemente las lineas NOP? O sea, tienen que llevar una instrucción necesariamente?

**Comment by FranLucchini** [comment]
No se pueden ignorar, la ROM no va a compilar si tiene menos líneas de las necesarias y lo importante es asegurarse de que las líneas que no son parte de su programa no afecten lo que se muestra en los registros.
