### ISSUE TITLE
Valores por defecto A,B

### ISSUE THREAD

**Issue by selira** [IIC2343-2016-2/syllabus#21]
En el assembly es necesario que al inicio de la parte de código se asuma que los registros tienen un valor por defecto, como 0, u otro que esté guardado de antes?

**Comment by FranLucchini** [comment]
Lo que puedo decir es que si no se han usado los registros, pueden asumir que guardan un cero, aunque eso no afecta al programa. Pero si los usaste para algo antes de que comience el código, entonces es necesario resetearlos al valor inicial: cero.

Lo que no me queda claro es porqué les surgió la duda de que deben asumir eso.

**Comment by selira** [comment]
es que les asignamos valores para guardar las variables en RAM en la parte de DATA:.
Además, podía ser que distintos programas se pudieran correr en forma sucesiva, de forma que se guarden los valores de A y B.
Gracias por responder
