### ISSUE TITLE
errores en archivos

### ISSUE THREAD

**Issue by rvcalderon** [IIC2343-2016-2/syllabus#22]
Hola! podemos asumir que los archivos vienen bien? con esto me refiero a que los registros A y B, ADD, MOV, ... estén con mayusculas y cosas de este estilo

Gracias!

**Comment by FranLucchini** [comment]
Sí, pueden asumirlo.

**Comment by fgvenegas** [comment]
Que cosas no podríamos asumir D:?

**Comment by FranLucchini** [comment]
Cualquier cosa que no salga en enunciado de Assembler.
