### ISSUE TITLE
Formato corrección entrega 2

### ISSUE THREAD

**Issue by FranLucchini** [IIC2343-2016-2/syllabus#23]
Saludos a todos,

Voy a describir cómo sera la corrección de la entrega 2. El Lunes voy a subir acá archivos en Assembly. Ustedes deberán compilar los .bit de cada archivo y subirlos a sus repositorios antes del Martes. 

El día de la corrección presencial, vamos a llamar a grupos al azar y nos deben mostrar sus .bit corriendo en la velocidad lenta o segunda más lenta. Los algoritmos se revisan como buenos o malos, no hay intermedios.

Los algoritmos, la formalidad y el informe los revisaremos nosotros después.

Les dejo la pauta de corrección:

| Test 1 | Test 2 | Test 3 | Test 4 | Test 5 | Test 6 | Algoritmos Div y Pow | Formalidad | Informe |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| 1 | 0.5 | 0.5 | 0.5 | 0.5 | 1 | 1 | 0.5 | 0.5 |

Que tengan un lindo fin de semana 💃

**Comment by icrocco** [comment]
Fran ¿hasta que hora tenemos entonces para subir todo? ¿17hrs. o 23:59? :grin:

Gracias

**Comment by FranLucchini** [comment]
23:59

**Comment by FranLucchini** [comment]
Archivos para la entrega
[AlgoritmosEntregaPresencial-E2.zip](https://github.com/IIC2343-2016-2/syllabus/files/493436/AlgoritmosEntregaPresencial-E2.zip)

**Comment by FranLucchini** [comment]
Sólo para confirmar que no hay una confuzión, las cosas las deben subir las cosas hoy a las 23:59

**Comment by jtagle2** [comment]
>  Los algoritmos se revisan como buenos o malos, no hay intermedios.
Puedo suponer entonces que si termino de ejecutar el programa con mi placa y en ambos registros aparece un 10, entonces está bien? (obviamente no está hardcodeado)

**Comment by FranLucchini** [comment]
Sip, creo que todos resultan en 10 10
