### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by PabloAbara** [IIC2343-2016-2/syllabus#24]
Hola, 
Tenemos dudas con respecto a cuando quiero guardar un Label. 
1) 
Tengo que guardar el índice asociado a la línea de instrucciones en ASSEMBLY (Líneas de instrucciones)? o a la de MI LISTA de instrucciones-OPCODES (considerando, por ejemplo, que cada instrucción puede no ser soportada por 1 línea de OPCODE, además de que al inicio debo agregar instrucciones asociadas a la DATA). 

2) La otra duda también es con labels pero en cuánto al direccionamiento. 

Es correcto pensarlo de la siguiente forma?
Data: 
Var1     2
CODE: 
MOV A,Var1 // Guardo en A el valor del direccionamiento de Var1 || A = 0
//Además el OPCODE asociado es del tipo MOV A,Lit
MOV A,(Var1)  // Guardo en A el valor que se encuentra en la memoria RAM  A = 2
//El OPCODE asociado es del tipo MOV A,(Dir) en donde el literal será 0

La duda surge ya que podría transformar de inmediato el (Var1) en 2 y en ese caso el OPCODE podría
ser del tipo MOV A,Lit. 

Gracias!!!

**Comment by MainScientist** [comment]
1) La idea es que guardes la referencia a la posicion en la ROM en lanque de encuentra la instruccion que sigue del label, es decir, a "tu" lista de instrucciones considerando que una linea de assembly puede requerir mas de una instruccion de maquina.
2) No puedes hacer eso que ya que el valor de Var2 en la memoria ram puede cambiar en cualquier momento, por lo que es incorrecto que lo 'hardcodees' en la ROM.

**Comment by PabloAbara** [comment]
Oka, entonces lo guardo en la lista 'desagregada' y ocupo el direccionamiento de la RAM para la 2). 

Gracias!!
