### ISSUE TITLE
¿El funcionamiento prectivo del program counter?

### ISSUE THREAD

**Issue by perojas3** [IIC2343-2016-2/syllabus#26]
Tengo la siguiente duda. Tratando de testear el program counter para saver como funciona, lo conecte a los display. Pero solo me muetra un 8 en cada display ¿Esto es ok? ¿Que esta pasando? ¿Esta cada display cambiando tan rapido que al ojo humano parece un 8?
En ese ultimo caso, significa que el pc va de 0 a 2^12-1 en un instante. Osea ¿Vuelve a empezar desde 0 cuando llega a 2^12-1?
¿Como evitamos que se repita entonces?

**Comment by MainScientist** [comment]
El pc es simplemente un registro que almacena el numero de la instruccion que se va a ejecutar, este puede ser sobrescrito y por defecto aumenta en uno en cada ciclo. Debes asegurarte de conectarle el clock que sale de la entidad ClockDivider y no hay problema con que el program counter vuelva a 0 una vez que alcanza su valor maximo.

**Comment by perojas3** [comment]
Sí, esta conectado al clk, no al clock, pero aun así tengo el problema. Avanza tan rapido que no puedo obsevar lo que se esta testeando. Es que avansa en in instante 2^12-1, incluso en lento.

**Comment by MainScientist** [comment]
Eso no deberia pasar, esta pusheado el codigo en su repo?

**Comment by FranLucchini** [comment]
De todas formas, la señal correcta se llama clock y hay que setear la velocidad del clock divider a 11 que es la más lenta.
