### ISSUE TITLE
Duda Ejemplo 8

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2343-2016-2/syllabus#27]
Hola, ejecute el código del ejemplo 8 y no nos funcionaba. Los valores que mostraba nuestra placa no correspondía con los que estaban comentados en el código. Hice todo el código con lápiz y papel para saber que valores tenían que mostrar A y B para cada instrucción y me dio algo distinto a lo que tenian comentado en el código ejemplo, por lo que estoy adjuntando mi código comentado por mi más abajo.
Pueden revisar por favor si lo que yo comente está bien? Para saber si estamos haciendo un error está en otra parte o en caso de que el ejemplo este malo, que el resto del curso sepa también. 
Saludos

`
DATA:
 v1 1100b
 v2 0101b
 v3 0h
CODE:
 MOV A,(v1)   // A=Mem[v1]=12.....................(0C,00)
 AND B,(v2)   // B=A|Mem[v2]=4....................(0C,04)
 XOR A,(v2)   // A=A^Mem[v2]=9...................(09,04) 
 AND A,B      // A=A&B=0................................(00,04)
 NOT (v3),A   // Mem[v3]=~A=FFFFh............(00,04)
 OR A,B       // A=A|B=4...............................(04,04)
 ADD A,(v3)   // A=A&Mem[v3]=3..................(03,04)
 AND A,1      // A=A&1=1................................(01,04)
 JNE inpar
 NOT B,A      // B=~A=FFFEh........................(01,FE) No pasa por acá
 XOR A,B      // A=A^B=FFFFh......................(FF,FE) No pasa por acá
 AND B,A      // B=A&B=FFFEh......................(FF,FE) No pasa por acá
 inpar:
 SHL B,A      // B=A<<1=2...............................(01,02)
`

**Comment by FranLucchini** [comment]
Puede ser que tenga un error, el que manda es el assembler del curso. Si muestra lo mismo debería estar correcto.
