### ISSUE TITLE
Tabla a entregar en el informe

### ISSUE THREAD

**Issue by jtagle2** [IIC2343-2016-2/syllabus#28]
En el enunciado dice que tenemos que entregar "un breve informe que contenga la especificación de la estructura de las instrucciones de su CPU (función de cada uno de los 33 bits de una instrucción), más una tabla con todas las instrucciones soportadas por la CPU y su implementación de acuerdo a la especificación indicada anteriormente".
Esto a que se refiere? Tenemos que poner una tabla con las instrucciones que están en el assembler, y ponerle sus opcodes y señales de control asociadas?

**Comment by FranLucchini** [comment]
>  Tenemos que poner una tabla con las instrucciones que están en el assembler, y ponerle sus opcodes y señales de control asociadas?

Sí, deben entregar esa tabla más los detalles de su implementación de las instrucciones de la ROM y de los MUX.
