### ISSUE TITLE
Tarea 3 

### ISSUE THREAD

**Issue by Zanfor** [IIC2343-2016-2/syllabus#30]
Podemos asumir que en el DAG que nos van a entregar, si es factible, todos los caminos llegan al end o podría perderse? Por ejemplo en este DAG, si el programa parte del 1 y quiere llegar al 8, podría irse por el camino de arriba y terminar en el 7 respondiendo False (0) , siendo que si hay una ruta del 1 al 8. Podemos asumir que los grafos no serán de esta forma o asumimos que si pueden serlo en cuyo caso tenemos que hacer una solución con backtracking?  
![dag](https://cloud.githubusercontent.com/assets/17620265/18840611/884dff2e-83e5-11e6-8802-2aca81474791.png)

**Comment by FranLucchini** [comment]
Err... Esto es de la tarea? Mejor preguntar al profesor o a los ayudantes
de tareas (patricio).

**Comment by tamycova** [comment]
@Zanfor averiguaste?
