### ISSUE TITLE
Formato prueba programa División y Potencia

### ISSUE THREAD

**Issue by PabloAbara** [IIC2343-2016-2/syllabus#31]
Hola! 

Tenemos la siguiente duda con respecto a la implementación; 
La entrega debería ser que cuando reciba un input con POW A,B 7 obtenga en A el resultado? 
O es programar en Assembly una secuencia que obtenga dichos valores y que el resultado se registre en A?
EN el fondo
(
MOV A,(Dir)
SUB A,B... etc...  
)
Gracias!!

**Comment by FranLucchini** [comment]
Es lo segundo que dijiste, ustedes deben programar en assembly un algoritmo que tome dos valores y luego muestre en A el resultado del elevado y deben hacer otro algoritmo para la división.

**Comment by PabloAbara** [comment]
Ahhhhhhh, muchas gracias!! (Sobre todo por la velocidad)

**Comment by PabloAbara** [comment]
Fran, sólo para evitar una mala interpretación. La entrega es un .txt con instrucciones en Assembly que haga lo que me piden a través de mis operaciones conocidas?. No tengo que implementar ni recibir un POW A,B/DIV A,B verdad?

**Comment by FranLucchini** [comment]
Exactamente

**Comment by PabloAbara** [comment]
:)
