### ISSUE TITLE
Implementación ADD B,Lit y ADD (Dir), B

### ISSUE THREAD

**Issue by gantunesr** [IIC2343-2016-2/syllabus#32]
Como se puede implementar las instrucciones ADD B,Lit y ADD (Dir),B que no son soportadas en un ciclo?

**Comment by FranLucchini** [comment]
Ambos casos pueden ser implementado en un ciclo. Hay algo que les sugiera
lo contrario? De todas formas, si les parece mascotas sencillo manejarlo en
dos pasos, van a tener que manejarlo desde el assembler y van a necesitar
dos opcodes para hacer la instrucción.  O sea, cuando el assembler lea ADD
B, Lit, por ejemplo,  en vez de imprimir un opcode, ingesa dos.
