### ISSUE TITLE
Problema con los switches

### ISSUE THREAD

**Issue by abannura** [IIC2343-2016-2/syllabus#35]
Al conectar el resto de los switches (13 nuevos, 16 en total) vivado nos tira el siguiente error:

[DRC 23-20] Rule violation (NSTD-1) Unspecified I/O Standard - 13 out of 35 logical ports use I/O standard (IOSTANDARD) value 'DEFAULT', instead of a user assigned specific value. This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all I/O standards. This design will fail to generate a bitstream unless all logical ports have a user specified I/O standard value defined. To allow bitstream creation with unspecified I/O standard values (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks NSTD-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run. Problem ports: sw[15:0].

Creemos que se debe a que de cierta manera los 13 nuevos switches no estan "activados" y que hay configurar la placa para usarlos. Alguna idea para solucionar esto? Muchas gracias.

**Comment by abannura** [comment]
Al final era porque en el archivo Basys3.xdc que esta en la carpeta constraints, los demas switches (del 4 al 16) estaban comentados con #. Habia que quitarle los asteriscos nomas.

**Comment by ignaciohermosillacornejo** [comment]
Buena Banura, tuve el mismo problema! gracias por publicar la solución!
