### ISSUE TITLE
Duda Subrutinas

### ISSUE THREAD

**Issue by difischer** [IIC2343-2016-2/syllabus#36]
En la entrega dice
"Para esto, las subrutinas generadas deben recibir el tamaño del arreglo desde el registro A y un puntero
desde el registro B, y de ser necesario retornen el resultado en A."
Como es esto? Al programa la placa le entrega el valor de A y B o que?  😖

**Comment by FranLucchini** [comment]
A lo que se refiere es a que ustedes pongan esos valores en A y B antes de comenzar el algortimo. No se refiere a que vengan predefinidos en los registros.

En verdad, lo importante de esto es que tengan en alguna parte guardado el largo del arreglo y un puntero a él. Si les complica esto, pueden guardarlo como variables en DATA.

**Comment by javierlopeza** [comment]
@FranLucchini Para el cálculo de la mediana (en caso de arreglos de largo par) y el promedio ¿dejamos los resultados aproximados a enteros (usamos división entera)?

**Comment by FranLucchini** [comment]
Sí, al igual qur lo hemos estado haciendo hasta ahora, trabajaremos con enteros aproximados. Si esto les preocupa, pieden definir cómo lo hacen en el informe.
