### ISSUE TITLE
Instrucción INC (B)

### ISSUE THREAD

**Issue by sofizambrano** [IIC2343-2016-2/syllabus#38]
Para poder ejecutar las instrucciones que tienen direccionamiento por registro (B) se necesita leer de la RAM con el valor que este en B y, además, escribir en ella el resultado de la operación. Se podría hacer esto en un mismo ciclo?

**Comment by FranLucchini** [comment]
Yo creo que sí. Si lo analizamos,  es similar a hacer una escritura en la ram usando el direccionamiento directo. Mantiene a B como la direccion de escritura y lo que llegue por datain se guarda al llegar la señal W.
