### ISSUE TITLE
Duda implementacion "CALL Dir"

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2343-2016-2/syllabus#39]
Tenía la siguiente duda, según el enunciado la instrucción CALL Dir se ejecuta en 3 pasos
1.- Mem[SP] = PC
2.- PC = Dir
3.- SP--
Mi duda es la siguiente, como se puede implementar la primera instrucción. Viendo el dibujo del computador básico que sale en el enunciado de la entrega 3, el PC solo se conecta a la ROM y al Adder, por lo que no podemos hacer pasar un valor desde el PC hasta la RAM sin que el Adder necesariamente le sume +1 por lo que en realidad estariamos implementando Mem[SP] = PC + 1
¿Hay algo que entendí mal o que puedo hacer para implementar CALL Dir en este caso?

**Comment by ignaciohermosillacornejo** [comment]
Lei nuevamente las instrucciones del Assembler y ahi sale que dentro de CALL Dir se tiene que implementar usando  Mem[SP] = PC + 1. Por lo tanto la instruccion CALL Dir dentro del enunciado de la entrega 3 debe estar malo

**Comment by FranLucchini** [comment]
Tienes razón,  lo correcto es lo que aparece en el enunciado del assembler.
