### ISSUE TITLE
Increase y decrease A entrega 2

### ISSUE THREAD

**Issue by sebamenabar** [IIC2343-2016-2/syllabus#4]
Para las funciones que tiene que soportar el assembly para el proyecto, las instrucciones INC A y DEC A no se pueden realizar en una única instrucción con la microarquitectura entregada, tenemos que hacer que se implemente igual pero en 2 instrucciones?

**Comment by FranLucchini** [comment]
Pueden hacer eso.. lo tendría que manejar el assembler.
