### ISSUE TITLE
Conexiones

### ISSUE THREAD

**Issue by jtagle2** [IIC2343-2016-2/syllabus#41]
Hay algunas conexiones que no me quedan claras con el diagrama o me estoy enredando. Las conexiones vendrían siendo:
Al Mux S, las direcciones de entrada vienen desde el SP, el literal y el Registro b
Al MUX Pc le entra RAM y Literal
Es así?
Saludos

**Comment by FranLucchini** [comment]
Sí, exactamente. Tienen alguna duda relacionada con eso?

**Comment by jtagle2** [comment]
No! Solo era eso. Gracias!
