### ISSUE TITLE
Entrega Proyecto

### ISSUE THREAD

**Issue by difischer** [IIC2343-2016-2/syllabus#42]
Según entiendo en la guía tenemos que entregar mañana los 4 programas de los arreglos que aparecen en la parte 3 de la guía ¿Esto es así o hay que entregar algo más?
Sobre esos mismos programas ¿Para evaluarlos podemos poner el arreglo que queramos nosotros o nos van a entregar uno?
🐍

**Comment by FranLucchini** [comment]
Deben subir los algoritmos estadísticos su repositorio y los evaluaremos fuera de ese horario y personalmente. Mañana solo deben tener los .bit de los algoritmos que les subiré mañana.

Sobre el arreglo, pueden poner uno de su preferencia en DATA, pero igual voy a probar algunos distintos.
