### ISSUE TITLE
Duda sobre el in

### ISSUE THREAD

**Issue by perojas3** [IIC2343-2016-2/syllabus#43]
En la pagina 3 del enunciado, dice que si  el literal es 0, el mx in devera dejar pasar los switches, pero si es 1 debera dejar pasar los botones. Lo que me confunde. El diagrama hace parecer que el 0 es a los 4 botones en forma de "+" y 1 para las 16 palancas. ¿Cual es cual?

**Comment by FranLucchini** [comment]
El diagrama es solo explkcativo, deben seguir lo que dicta la tabla: 0 es de los switches y 1 de los botones. No se compliquen por eso.

**Comment by perojas3** [comment]
¿Cual es la diferencia entre switches y botones? ¿Cual es cual?

**Comment by FranLucchini** [comment]
Los switches so las palanquitas de la placa y los botones son los cinco botones en forma de cruz
