### ISSUE TITLE
Test numero3 Duda sobre IN

### ISSUE THREAD

**Issue by abannura** [IIC2343-2016-2/syllabus#44]
En el test 3 hay un IN que recibe como literal el 2, pero tenia entendido que el literal (al menos para esta entrega) podia solo ser 0 o 1 (switches o botones). Gracias

**Comment by FranLucchini** [comment]
Es verdad, pero eso está ahí para asegurarse de que traigan los valores del
muxIN usando los 16 bits y no sólo 1 bit.

**Comment by jtagle2** [comment]
Fran, respecto a eso. Si yo le entrego `0000000000000010`, el input leído deberá ser el correspondiente a los switches? Porque el output del MuxIn, no puede ser "nada".
En otras palabras, si bien recibo 16 bits, corroboro el bit menos significativo? O la palabra completa debe ser 0 o 1?
Saludos

**Comment by FranLucchini** [comment]
La idea es que el valor que le llega, si no es 00...00 o 00...01, debe ser cero.
