### ISSUE TITLE
Duda ayudantía mañana

### ISSUE THREAD

**Issue by difischer** [IIC2343-2016-2/syllabus#45]
Fran, en el mail que mandaste dice:
`El horario de ayudantía del lunes 24 de octubre va a quedar para re-corrección de la E3` esto significa que no hay ayudantía en el caso de que el grupo no tiene nada que recorregir?

Gracias de antemano :snake:

**Comment by FranLucchini** [comment]
Exactamente, no hay ayudantía hoy, sólo la recorrección.

**Comment by FranLucchini** [comment]
Exactamente
