### ISSUE TITLE
Error Ejemplo Assembler y duda definición caracteres/strings

### ISSUE THREAD

**Issue by flobarrios** [IIC2343-2016-2/syllabus#46]
Hola! Creo que hay un error en un ejemplo dado y quiero confirmarlo 😊.

```
DATA:
 letrac ’c’     // 99
 string "ho la" // [’h’, ’o’, ’ ’, ’l’, ’a’, 0] = [104, 111, 20, 108, 97, 0]
CODE:
 MOV A,(letrac) // A = 99
 SUB A,’a’      // A = A - 97 = 2 
```

En este caso, creo que el espacio en "ho la" debiese ser 32 y no 20.

Por otro lado, solo para confirmar, cuando se define un caracter siempre va a ser entre comillas simples y un string con comillas dobles ? O mejor diferencio por el largo del string/caracter?

Gracias!

**Comment by flobarrios** [comment]
Y otra cosa, es esto válido?

```
arreglo 0
        101b 
        2h 
        7d
        'c'
        "hola"
```
O puedo asumir que los caracteres y strings se presentarán siempre por separado, y no mezclados con arreglos de números (como el ejemplo que puse antes)?

Gracias!

**Comment by FranLucchini** [comment]
Ok, vamos una por uno

> En este caso, creo que el espacio en "ho la" debiese ser 32 y no 20.

Por qué lo dices? Rivisé la tabla que indica los valores y el valor 0001 0100 (20) corresponde a un espacio.

> Por otro lado, solo para confirmar, cuando se define un caracter siempre va a ser entre comillas simples y un string con comillas dobles ? O mejor diferencio por el largo del string/caracter?

Exactamente, al igual que algunos lenguajes de programación (C++. C#, Java, etc..)

> Y otra cosa, es esto válido?

Nope, los arreglos son o de caracteres o de números, no hay mezcla de tipos.

**Comment by flobarrios** [comment]
Yo estoy mirando [esta](http://ascii.cl) tabla y en decimal, equivale a 32 y en hex a 20, pero todos los otros están en decimal, por eso pregunto!

Lo último, se que es sutil jaja pero la comilla simple será: ’ o '  (o cualquiera de las 2)

Gracias!!

**Comment by FranLucchini** [comment]
La tabla que deben mirar es la que está en el pdf llamado "Manual PmodCLP", pág 5. Este archivo está en la página del siding en `Proyecto/Documentos/Archivos necesarios para  la E4.
`
El uso de ambas depende de ustedes, pero en los ejemplos que vamos a probar y lo mínimo que deben tener, es la comilla simple ( ' ). La invertida ( ` ) no es necesaria.

**Comment by flobarrios** [comment]
Ok gracias!!

**Comment by flobarrios** [comment]
Fran me queda una duda, en el enunciado dice: aceptar literales como caracteres desde el 32 al 126 de la tabla ASCII, en el formato ’c’.

Esto es respecto a la tabla de ```Proyecto/Documentos/Archivos necesarios para la E4```? Si es asi, el espacio no podría ser el 20 ya que no esta dentro de ese rango, y seria el 32 (que de acuerdo a la tabla, también corresponde a un espacio). Por lo tanto, tenemos que fijarnos únicamente en estos caracteres (00100000 al 01111110)?:

![screen shot 2016-10-26 at 9 37 17 pm](https://cloud.githubusercontent.com/assets/11543803/19750049/6a5301bc-9bc4-11e6-9856-15f865976187.png)

Perdón si estoy entendiendo algo mal ! jajaja

**Comment by FranLucchini** [comment]
No, lo que dice es que hay que soportar caracteres como los de la tabla
ASCII, para mostrar cuáles de los caracteres de la deben mostrar, pero eso
no limita los valores posibles que pueden entregarse. Toda la tabla es
soportada por la tabla.

La idea de este rango es que no esperen recibir los caracteres japoneses
que se muestran en la tabla.
