### ISSUE TITLE
Duda Reg Dis y Reg Led

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2343-2016-2/syllabus#47]
Fran, estaba revisando el diagrama de los registros a implementar y me fije que tanto el Reg Dis y el Reg Led reciben input desde el Decoder Out y el Registro B. Lo que me pasa es que no veo en el diagrama una señal de control para los Registros Dis y Led, pero asumí que deben tener una. ¿Es correcto lo que asumí?

EDIT: Estuve leyendo las notas que tome esta mañana en el taller y mi pregunta cambio un poco. Por lo que entendí del taller y leyendo el enunciado, el Decoder Out es un mux que tiene 3 salidas de 1 bit conectadas al Display, Leds y LCD, donde puede enviar como máximo 1 bit con el valor de 1 a la vez a una de las tres salidas mencionadas anteriormente. 
Además, la salida selecionada va a depender del valor que salga desde el Mux B donde por ejemplo; si de Mux B sale "00....0001" entonces el Decoder Out va a enviar a el Registro LED un 1. De la misma forma, si del Mux B sale "00...00010" entonces el Decoder Out va a enviar al Reg Dis un valor de 1.
Por el contexto, inferí que los bits que salen desde el Decoder Out hacia los dos registros corresponderían a la señal de enable y el valor del registro A correspondería al contenido a cargar. 
Finalmente, queria preguntar cual es la función de la señal de control loadOut, ¿hace que el Decoder Out solo pueda sacar valores distintos a 0 cuando su valor sea 1?

**Comment by FranLucchini** [comment]
Bueno, como inferiste del decoderOUT salen las señales de control para esos elementos. Por otra parte, considera que no existiera LoadOUT, qué pasaría? El valor que viene del MuxB siempre se expresaría en los registros, pero no queremos que haga eso. Entonces, añadimos la señal de control LoadOUT para que los valores del decoder lleguen a los registros sólo cuando se está ejecutando la instrucción OUT.

**Comment by ignaciohermosillacornejo** [comment]
Gracias Fran

**Comment by abannura** [comment]
Buena hermo, respecto a lo que dijiste sobre la entrada al decoder, no deberia ser si lo que sale del MUXB es "0000..00" (16 ceros), entonces ahi va al RegDis? Y si es "0000..01" va al RegLed, y por ultimo si es "0000..10" va al LCD? En cualquier otro caso, las tres senhales seran cero. En el fondo, se cuentan las direcciones de output como 0,1,2 o como 1,2,4? Gracias

**Comment by ignaciohermosillacornejo** [comment]
Yo lo hice como 0,1 y 2






On Fri, Nov 4, 2016 at 2:16 PM -0400, "abannura" <notifications@github.com> wrote:












Buena hermo, respecto a lo que dijiste sobre la entrada al decoder, no deberia ser si lo que sale del MUXB es "0000..00" (16 ceros), entonces ahi va al RegDis? Y si es "0000..01" va al RegLed, y por ultimo si es "0000..10" va al LCD? En cualquier otro caso, las tres senhales seran cero. En el fondo, se cuentan las direcciones de output como 0,1,2 o como 1,2,4? Gracias

**Comment by FranLucchini** [comment]
Deben hacerlo como 0, 1 y 2 o la librería no funcionará correctamente.
