### ISSUE TITLE
Duda Conección Decoder Out con LCD y Registro A

### ISSUE THREAD

**Issue by ignaciohermosillacornejo** [IIC2343-2016-2/syllabus#49]
El bus de entrada al LCD es de 11 bits y el enunciado dice que el bit que proviene del Decoder Out es el más significativo. Mi duda es sobre los 10 bits restantes que vienen del Registro A ya que la salida del Registro A tiene 16 bits. Conecto los 10 bits más o menos significativos que salen del Registro A?

**Comment by FranLucchini** [comment]
Deben ser los 10 menos significativos.

**Comment by ignaciohermosillacornejo** [comment]
Gracias Fran

**Comment by bmarinb** [comment]
@FranLucchini  Al momento de crear la señal de 11 bits, ¿cuál señal es la más significativa, la del decoder o la del registro A?

**Comment by ignaciohermosillacornejo** [comment]
La del Decoder






On Fri, Nov 4, 2016 at 1:27 PM -0400, "bmarinb" <notifications@github.com> wrote:












@FranLucchini  Al momento de crear la señal de 11 bits, ¿cuál señal es la más significativa, la del decoder o la del registro A?

**Comment by bmarinb** [comment]
Gracias!

**Comment by abannura** [comment]
Otra duda respecto a esto, que tenemos que hacer con los 3 bits que sobran para los lcd? Pq tengo 10 bits del RegA y uno del Decoder, pero los lcd de la placa tienen 8 bits nomas? O me equivoco?

**Comment by ignaciohermosillacornejo** [comment]
El input del lcd es de 11 bits tengo entendido. Sale explicado en otro issie que abri






On Fri, Nov 4, 2016 at 3:08 PM -0400, "abannura" <notifications@github.com> wrote:












Otra duda respecto a esto, que tenemos que hacer con los 3 bits que sobran para los lcd? Pq tengo 10 bits del RegA y uno del Decoder, pero los lcd de la placa tienen 8 bits nomas? O me equivoco?

**Comment by FranLucchini** [comment]
Es cierto, la placa recibe 11 bits, algunos son de datos pero otros son flags para intrucciones.
