### ISSUE TITLE
¿Que habia que hacer con los constraints?

### ISSUE THREAD

**Issue by perojas3** [IIC2343-2016-2/syllabus#51]
Recuerdo que habia que descomentar un constraint. ¿Pero cual era?
Y ¿Cual es el nombre estandar que le dimos en el archivo basis3?

**Comment by FranLucchini** [comment]
El nombre del archivo es Basys3.xdc y debería estar en la carpeta del proyecto dentro de` constrs_1/new`. Hay que descomentar todos los pins asociados al arreglo lcd.  La solución dada [aquí](https://github.com/IIC2343-2016-2/syllabus/issues/50) puede ayudarte.

**Comment by perojas3** [comment]
¿No hay que descomentar ninguno que tenga dobre #?
