### ISSUE TITLE
Dudas generales de la entrega 4

### ISSUE THREAD

**Issue by perojas3** [IIC2343-2016-2/syllabus#52]
Tengo las siguientes dudas respecto a la entrega 4
1.- El enunciado dice que se nos entregara un timer, y un nuevo Clock_Divider y Debouncer. Pero ya teniamos un timer de antes, el cual es identico al nuevo que nos entregaron, y no nos dieron ningun nuevo Clock_Divider y Debouncer. ¿Que pasa alli?
2.- Sobre el sistema al rededor del Decorde Out, la señal lcd recive 11 bits, 10 de los cuales vienen del registro A y un ultimo del Decoder ¿Cuales son esos 10 del registo A?
3.- El sistema al rededor del Decorde Out tiene 2 restros, el data in esta conectado al resgisto A. ¿pero los bits que vienen del decoder out estan conectados a el load? ¿De ser así, como el decoder funciona como "control"?

**Comment by FranLucchini** [comment]
Vamos uno por uno:
1. Eso es un error arrastrado del semestre anterior. Como ya tienen esos componentes,  pueden ignorar esos pasos.
2. Del registro A deben mandar los 10 menos sign
3. No entiendo muy bieb la pregunta, pero la idea es que cuando entre una instrucción OUT a la control unit, esta debe hacer que LoadOUT sea 1. Ahora, cuando llega un valor al decoder la traduce en señales de control para los registros. En el caso de la LCD, para poder escribir en ella, el bit más significativo debe estar en uno y los otros 10 son datos que van a la LCD.

**Comment by perojas3** [comment]
Con la 3 me referia al registro dis, y al registro led. ¿A donde se conecta la señal del decoder?

**Comment by FranLucchini** [comment]
Ah, perfecto. La idea es que la señal del decoder entre a la entrada Load del registro.

**Comment by perojas3** [comment]
Una pregunta más. El clock de esta entrega lo ponemos en la maxima velocidad, verdad?

**Comment by FranLucchini** [comment]
Exactamente, debe ir en la velocidad 00. Pero, recuerda que el timer usa la señal clk.

**Comment by perojas3** [comment]
Una pregunta más, considerando todos los componentes de  la entrega, ¿Cuales usan clk, y cuales clock?

**Comment by FranLucchini** [comment]
Todos los que vienen de la entrega 3 usan clock. También el RegDis y el
RegLed. El único que necesita el clk es el timer.
