### ISSUE TITLE
salidas c, z, n

### ISSUE THREAD

**Issue by glbello** [IIC2343-2016-2/syllabus#62]
Saludos, en el enunciado no entiendo muy bien la función de las salidas, c, z y n, ejemplo en el add donde dice para el c: *result < a + b* no entiendo que significa, para shr que se refiere con *a(0)* y en shl *a(15)*.

**Comment by FranLucchini** [comment]
Eso lo puedes interpretar como una condición booleana de un "if". En ese caso, esto se lee:

c = 1 si el resultado de la suma es menor a + b (eso ocurriría en caso de que el espacio de bits se te acaba y queda un carry) y c = 0 en otro caso.

**Comment by glbello** [comment]
gracias, creo entender eso de la resta que parece intuitivo, pero para los otros casos, como el:
- result < a + b
- shr con a(0)
- shl(15)
¿como los interpreto?

**Comment by FranLucchini** [comment]
Buenos, las señales N y Z corresponden a la señal de negatividad y Cero espectivamente (deberían pasarlas en clases). La señal N se pregunta si a es menor que b y la señal Z se pregunta si a es igual a b.

La idea de esta tabla de verdad es expresar dada una operación, en qué casos deben encenderse las señales de contro, C, Z y N. Entonces, por ejemplo, si en el shl dice que C = a[15], quiere decir que, como al hacer el shift estás "botando" el bit 15, su valor corresponde a la señal C. De esta misma forma se pueden interpretar el caso en que C = a[0] y la condición booleana result < a+b
