### ISSUE TITLE
Flags Z, N, C

### ISSUE THREAD

**Issue by IgnacioTobar** [IIC2343-2016-2/syllabus#65]
No entiendo esta parte del enunciado

"Al activarse los ﬂags de la ALU (Z, N y/o C) y la señal “clock” deben encenderse correspondientemente los 4 leds disponibles en ese orden. "

"Operaciones: Agregar y completar la ALU, conectando los switches para poder seleccionar la operación y los leds para ver los ﬂags."

Dice que los flags Z, N, C se "activan" y debes poder "verlos", pero lo que se ve en los leds es el resultado, ¿no? Una vez que se calcula Z, N y C y "salen" de la ALU ¿hay que conectarlos a alguna otra señal o hacer algo con ellos?

**Comment by FranLucchini** [comment]
Como tú dices, hay que conectar las señales Z, N y C a los leds para poder ver su resultado. Por ahora no hay más que hacer con ellos.
