### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by Bnnunez** [IIC2343-2016-2/syllabus#66]
Se pueden usar loops para la multiplicación?

**Comment by Hernan4444** [comment]
@Bnnunez la idea es usar los contenidos que hasta ahora han visto en el curso para crear la multiplicación.
Como hint: te puedo mencionar el Shift y suma.
pd: Como una multiplicación de n x n bytes crea un resultado de largo 2n, puedes considerar solo el producto entre A y B usando los 8 bytes menos significativos para que el resultado sea de 16 bytes y se aprecie todo en el display.

Saludos!

**Comment by FranLucchini** [comment]
Si lo vas a usar para sumar "n" veces el otro número, entonces no es correcto.

**Comment by Bnnunez** [comment]
Entonces se puede para los shift pero no para el valor normal. Pero si se puede con loops

**Comment by Hernan4444** [comment]
@Bnnunez eso si puedes.
Saludos
