### ISSUE TITLE
VM

### ISSUE THREAD

**Issue by tamycova** [IIC2343-2016-2/syllabus#7]
No logramos que Vivado reconozca la placa en la VM, alguien que le funcione??

**Comment by Hernan4444** [comment]
@tamycova a mi me paso eso en 3 ocasiones por diversos motivos.
1) No tenia instalado los drivers, reinstale el programa y me asegure de aceptar instalar los drivers.
2) El cable estaba medio malo así que lo cambie.
3) Tenia apagada la placa, hay un switch cerca de donde se conecta el micro usb que dice si esta prendida o no.
Ojala sea una de esas 3 cosas.
Saludos!

**Comment by gantunesr** [comment]
@Hernan4444 Como se si tengo los drivers instalados?

**Comment by Hernan4444** [comment]
@gantunesr En general, si tu pc reacciona con la placa al momento de conectarla (como si fuera una pendrive que se conectó) es un síntoma de drivers instalados,.
La otra opción es abrir en la carpeta de vivado el exe "Add Design Tools or Devices 2016.2" y ahi poner que quieres instalar los drivers (si es que ya están te dirá que no es necesario instalarlos)
