### ISSUE TITLE
archivo .tex?

### ISSUE THREAD

**Issue by glbello** [IIC2343-2016-2/syllabus#70]
Saludos!

Quería saber que era este archivo, y cómo abrirlo que parece tener información útil pero abriendolo desde un editor de texto no parece ser la mejor opción.
![pregunta](https://cloud.githubusercontent.com/assets/13740193/25551416/13a916ee-2c5b-11e7-8128-d57efa12c967.jpg)

**Comment by Hernan4444** [comment]
@glbello es lo mismo que el pdf de assembler pero en otro formato que permite su edición, fue un ligero error por parte nuestra subir ese.

Saludos!

**Comment by glbello** [comment]
Perfect, muchas gracias!
