### ISSUE TITLE
Respuesta a dudas de Assembler y componentes E2

### ISSUE THREAD

**Issue by FranLucchini** [IIC2343-2016-2/syllabus#8]
Subo dudas que me han presentado algunos de sus compañeros:
@andersskog 

> 1) En el assembly existen como 2 elevado a 7 operaciones distintas. Esto significa que necesitaremos opcodes de 7 bits nomas. Porque en el diagrama del computador básico de la entrega entran 17 bits al control unit? Son necesarios? En caso de no utilizarlos, los debemos dejar en 0 o eliminarlos quizás?

Bueno, como tú dices les van a sobrar bits, pero este tamaño está pensado para un caso escalable. En caso de no utilizarlos deben dejarlos en 0.

> 2) De que manera funciona el Control Unit? Entra un opcode y acá con if y else se determina que señales enviar?

El funcionamiento interno de la contro unit depende de ustedes. Pueden usar bloques de if/else dentro de ella. En lo que respecta al funcionamiento externo, le deben llegar los opcodes y las señales del registro status (N,Z,C) como input y retornal las señales  de control para cada componente que las necesite.

**Comment by abannura** [comment]
Una duda relacionada: el bus que va de la ROM al PC cambia de tamaño (de 12 a 16 bits). Por un lado, el enunciado indica que la ROM tiene 4096 palabras (2^12) por lo que me hace sentido que sea 12 el valor correcto. Sin embargo, tambien se menciona que las palabras que salen de esta son de 33 bits (16+17). Que hago, acorto las palabras en la ROM a 29 bits (12+17) o aumento el tamaño de la ROM a 2^16 palabras. Muchas gracias de antemano!

**Comment by FranLucchini** [comment]
Saludos, no deben editar en ninguna forma la ROM, lo que deben hacer es añadir los bits necesarios. Además,  creo que hay una pequeña confusión, la conexión va desde el PC a la ROM para seleccionar una jntrucción y no al revés.

**Comment by bmarinb** [comment]
@FranLucchini Si no debo editar la ROM, ¿cómo guardo las señales la, lb, lpc, etc asociadas a cada opcode?

**Comment by FranLucchini** [comment]
Según la materia del computador básico, esas señales no se guardan. Lo que ocurre es que la Control Unit traduce cada opcode a las señales correspondientes en cada ciclo.

**Comment by bmarinb** [comment]
Pero la "traducción" tiene que estar en una ROM y para eso tendría que modificar la ROM

**Comment by FranLucchini** [comment]
A lo que me refería co no editar la ROM es que no deben modificar el funcionamiento,  pero sí deben ingresar las instrucciones que tienen el literal y el opcode. Pero la traducción ocurre en la control unit. 

Por ejemplo, si ustedes determinan que el opcode de MOV A, B es el 3, entonces en la ROM debe mandar ese opcode a la CU. Entonces, de alguna forma deben hacer que ese 3 se transforme en las señales necesarias para hacer MOV A, B.

**Comment by bmarinb** [comment]
Gracias!

**Comment by tamycova** [comment]
@FranLucchini en el diagrama hay 33 bits saliendo de la rom, 16 del literal y 17 de opcode, en el fondo el opcode es de 14 y las señales de registro 3? Y lo otro, el bus de address de la RAM es de 12 bits, osea cuando quiera acceder a la ram seria opcode + 12 bits de direccion ram + relleno? osea en la control unit debo diferenciar entre los que vienen con literal y direccion? perdon si es muy obvio jajaja estoy un poco confundida

**Comment by FranLucchini** [comment]
La señal que entra a la CU es del tamaño que ustedes determinen necesario. Si les sobran bits, los pueden descartar. Y exactamente, deben entrar las 3 señales del registro.

La CU no maneja los valores del literal. En las instrucciones de la ROM vas a tener el opcode y los 16 bits de literal (que pueden ser una dirección para la RAM o sólo un número) y te pueden sobrar algunos bits. Pero, de nuevo, el valor del literal no pasa por la CU.
