### ISSUE TITLE
Division

### ISSUE THREAD

**Issue by abannura** [IIC2343-2016-2/syllabus#9]
Para la division, es necesario calcular los decimales? En el enunciado sale que no es necesario mostrarlos en el resultado, sin embargo me surgio la duda sobre si hay que calcularlos igual (a pesar de que no se muestren). La duda me surgio porque, por ejemplo para la entrega 1, la suma igual la calculabamos para los 16 bits pero solo mostrabamos 8. Muchas gracias de antemano!

**Comment by FranLucchini** [comment]
No es necesario calcular los decimales, de hecho, es división entera.

**Comment by abannura** [comment]
Dale perfect! y asumimos complemento A2 no cierto? Es decir, puedo dividir numeros negativos. Gracias!

**Comment by abannura** [comment]
Y otra duda! Sorry lo chato, pero al calcular las potencias, si el exponente es negativo entonces el resultado es cero? Ya que la division es parte entera? Muchas gracias!

**Comment by FranLucchini** [comment]
Como habíamos hablado y como sale en el enunciado general  solo manejaremos números positivos.

**Comment by abannura** [comment]
Sorry, no se como se me paso! Muchas gracias!
